/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
 * Generated on: 12-Jun-2015 11:03:02 by Kremmen
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015a\extern\include\tmwtypes.h 
 */
const uint16_t NL = 5;
const float NUM[5] = {
    0.02800000086,  0.05299999937,  0.07100000232,  0.05299999937,  0.02800000086
};

const uint16_t DL = 5;
const float DEN[5] = {
	1.0,   -2.026000023,    2.148000002,   -1.159000039,   0.2790000141
};
